# Generated by Django 4.0 on 2022-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='complaint',
        ),
        migrations.AddField(
            model_name='progress',
            name='category',
            field=models.CharField(default='water', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='describe',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AllComplaints',
        ),
    ]
